import NavBar from "@/components/navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" data-theme="emerald">
      <body
        className={`flex flex-row text-blue-950 ${inter.className} h-screen`}
      >
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
