import NavBar from "@/components/navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" data-theme="nord">
      <body
        className={`p-4 flex text-blue-950 flex-col ${inter.className} overflow-auto`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
